# Generated by Django 5.2.16 on 2026-08-10 15:34

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='end_date',
            field=models.DateField(
                default=datetime.date(2027, 8, 31)
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='academicyear',
            name='is_current',
            field=models.BooleanField(default=False),
        ),

        migrations.AddField(
            model_name='academicyear',
            name='start_date',
            field=models.DateField(
                default=datetime.date(2026, 9, 1)
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='academicyear',
            name='year_name',
            field=models.CharField(
                default='2026-2027',
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]