# Generated by Django 5.2.16 on 2026-08-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_academicterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='academic_term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='core.academicterm'),
            preserve_default=False,
        ),
    ]
