# Generated by Django 5.2.16 on 2026-08-19 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_timetable_academic_term'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('exam_type', models.CharField(choices=[('Mid Term', 'Mid Term'), ('Final Exam', 'Final Exam'), ('Unit Test', 'Unit Test'), ('Quiz', 'Quiz'), ('Practical', 'Practical'), ('Assignment', 'Assignment')], max_length=30)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_marks', models.PositiveIntegerField()),
                ('passing_marks', models.PositiveIntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='core.academicterm')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='core.teachersubject')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
    ]
