# Generated by Django 5.2.16 on 2026-08-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='exam_room',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
