# Generated by Django 5.2.16 on 2026-08-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_examination_exam_room'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='exam_room',
        ),
        migrations.RemoveField(
            model_name='examination',
            name='teacher_assignment',
        ),
        migrations.AddField(
            model_name='examination',
            name='school_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='core.schoolclass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examination',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='examination',
            constraint=models.UniqueConstraint(fields=('academic_term', 'school_class', 'subject', 'exam_type'), name='unique_exam_per_subject'),
        ),
    ]
