# Generated by Django 5.2.16 on 2026-08-19 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_examination_exam_room_and_more'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examination',
            name='exam_name',
        ),
        migrations.CreateModel(
            name='ExamHallAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_allocations', to='core.examination')),
                ('invigilator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilations', to='core.teacher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_hall_allocations', to='core.section')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_hall_allocations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['section'],
                'constraints': [models.UniqueConstraint(fields=('examination', 'section'), name='unique_section_exam_allocation')],
            },
        ),
    ]
